<?php

/**
 * Blogroll
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Blogroll extends BaseBlogroll
{
	
	public static function get_all_blogs($limit = 0){
		$q = Doctrine_Query::CREATE()
				->select('b.*, u.*')
				->from('Blogroll b, b.Users u')
				->orderBy('b.created_on DESC')
				->limit($limit)
				->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
		
		return $q;
	}
	
	public static function delete_blog($blog_id){
		
		$q = Doctrine_Query::create()
			->delete('Blogroll b')
			->where('b.blog_id = ?', $blog_id)
			->execute();
		return $q;
	}
}