<?php

/**
 * Posts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Posts extends BasePosts
{
	public static function get_post_by_id($id){
		$q = Doctrine_Query::CREATE()
			->select('p.*')
			->from('Posts p')
			->where('p.post_id = ?', $id)
			->fetchOne();
		
		return $q;
	}
	
	public static function get_posts($limit, $req_ids = array()){
		$q = Doctrine_Query::CREATE()
			->select('p.*')
			->from('Posts p')
			->whereIn('p.post_id',$req_ids)
			->orderBy('p.post_date DESC')
			->limit($limit);
		
		return $q->execute(array(),Doctrine_core::HYDRATE_ARRAY);
	}
	
	public static function get_post_ids(){
		$q = Doctrine_Query::CREATE()
			->select('p.*')
			->from('Posts p')
			->orderBy('p.post_date DESC');
		
		return $q->execute(array(),Doctrine_core::HYDRATE_ARRAY);
	}
	
	
	public static function get_num_cards(){
		return Doctrine_Core::getTable('Posts')->findAll()->count();
	}
	
	function get_all_cards($start, $limit){
		$q = Doctrine_Query::create()
			->select('p.*')
			->from('Posts p')
			->whereNotIn('p.post_status',array('draft'))
			->offset($start)
			->limit($limit)
			->orderBy('p.post_date DESC');
			
		$cards = $q->execute(array(),Doctrine_core::HYDRATE_ARRAY);
		return $cards;
	}
}