<?php

/**
 * PostDonationRel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PostDonationRel extends BasePostDonationRel
{
	public static function get_by_post_id($post_id, $hydrate = Doctrine_core::HYDRATE_ARRAY){
		$q = Doctrine_Query::CREATE()
			->select('pdr.*, d.*')
			->from('PostDonationRel pdr, pdr.Donations d')
			->where('pdr.post_id = ?', $post_id);
			
		return $q->execute(array(), $hydrate);
	}
}