<?php

/**
 * Users
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Users extends BaseUsers
{
	private static $user;
	
	public static function find_by_id($id, $provider){
		$q = Doctrine_Query::CREATE()
			->select('*')
			->from('Users u')
			->where('u.oauth_uid = ?', $id)
			->andWhere('u.oauth_provider = ?', $provider)
			->fetchOne();
		
		return $q;
	}
	
	function login($oauth_id, $provider){
		$u = Doctrine_Query::CREATE()
			->select('*')
			->from('Users u')
			->where('u.oauth_uid = ?', $oauth_id)
			->andWhere('u.oauth_provider = ? ', $provider)
			->fetchOne();
		
		$CI =& get_instance();
		
		$session_data = array(
    							'user_id' => $u->user_id,
    							'username' => $u->username,
    							'oauth_uid' => $u->oauth_uid,
    							'oauth_token' => $u->oauth_token,
    							'oauth_secret' => $u->oauth_secret
    						);
    						
    	$CI->session->set_userdata($session_data);
    	self::$user = $u;
	}
	
	function user() {
		if(!isset(self::$user)) {
			$CI =& get_instance();
            $CI->load->library('session');
            
			if (!$user_id = $CI->session->userdata('user_id')) {
				return FALSE;
			}

			if (!$user = Doctrine::getTable('Users')->find($user_id)) {
				return FALSE;
			}

			self::$user = $user;
		}
		
		return self::$user;
	}
	
	
	function logout(){
		$session_data = array(
    							'user_id' => '',
    							'username' => '',
    							'oauth_uid' => '',
    							'oauth_token' => '',
    							'oauth_secret' => ''
    						);
		$this->session->unset_userdata($session_data);
		self::$user = null;
	}
	function __clone() {
		trigger_error('Unable to clone Users - restricted by administrator', E_USER_ERROR);
	}
}